---
title: "TCGAbiolinks: Searching and downloading mutation files"
date: "`r BiocStyle::doc_date()`"
vignette: >
  %\VignetteIndexEntry{"TCGAbiolinks: Searching and downloading mutation files"}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(progress = FALSE)
```

```{r message=FALSE, warning=FALSE, include=FALSE}
library(TCGAbiolinks)
library(SummarizedExperiment)
library(dplyr)
library(DT)
```


**TCGAbiolinks** has provided a few functions to download mutation data from GDC.
This section shows how to use the function `GDCquery_Maf`.


---

# Mutation data

This exmaple will download MAF (mutation annotation files) for variant calling pipeline muse.
Pipelines options are: muse, varscan2, somaticsniper, mutect. For more information please access
[GDC docs](https://docs.gdc.cancer.gov/Data/Bioinformatics_Pipelines/DNA_Seq_Variant_Calling_Pipeline/).

```{r results = 'hide', echo=TRUE, message=FALSE, warning=FALSE}
acc.maf <- GDCquery_Maf("ACC", pipelines = "muse")
```
```{r  echo = TRUE, message = FALSE, warning = FALSE}
# Only first 100 to make render faster
datatable(acc.maf[1:50,],
              filter = 'top',
              options = list(scrollX = TRUE, keys = TRUE, pageLength = 5), 
              rownames = FALSE)
```
